export const bgm = {
    one: "./assets/bgm/1.ogg",
    jaina: "./assets/bgm/1scary.ogg",
    two: "./assets/bgm/2.ogg",
    three: "./assets/bgm/3.ogg",
    four: "./assets/bgm/4.ogg",
    five: "./assets/bgm/5.ogg",
    six: "./assets/bgm/6.ogg",
    seven: "./assets/bgm/7.ogg",
    eight: "./assets/bgm/8.ogg",
    nine: "./assets/bgm/9.ogg",
    ten: "./assets/bgm/10.ogg",
    akira_theme: "./assets/bgm/akiraTheme.ogg",
    akira_creepy_theme: "./assets/bgm/ayanoThemeCreepy.ogg",
    mika_theme: "./assets/bgm/mikaTheme.ogg",
    aiko_theme: "./assets/bgm/Aiko_theme.mp3",
    sad_theme: "./assets/bgm/mika_theme_sad.mp3",
    blækvard: "./assets/bgm/squidward_theme.mp3",
    freddy: "./assets/bgm/Wwtbam.ogg",
    baldi: "./assets/bgm/scary_school_lesson.ogg",
    relax: "./assets/bgm/relax.ogg",
    creepy: "./assets/bgm/creepy.mp3",
    intense_quiz: "./assets/bgm/intense_quiz.mp3",
    very_happy: "./assets/bgm/Candy Hearts.ogg",
    emotinal_sad: "./assets/bgm/emotional_sad.mp3",
    sayonara_music_box: "./assets/bgm/Sayo-naraMusicBoxVersion.ogg",
};