export const characters = {
    eddy: {
      name: "Eddy",
      expressions: {
        eddyNeutral: "./assets/characters/eddy/eddyNeutral.png",
        eddyLookAway: "./assets/characters/eddy/eddyLookAway.png",
        eddyEvil: "./assets/characters/eddy/eddyEvil.png",
        eddyHappy: "./assets/characters/eddy/eddyHappy.png",
      },
    },
    helpy: {
      name: "Helpy",
      expressions: {
        helpyThinking: "./assets/characters/helpy/helpyThinking.png",
        helpyAngry: "./assets/characters/helpy/helpyAngry.png",
        helpydc: "./assets/characters/helpy/helpydc.png",
        helpydcLookAway: "./assets/characters/helpy/helpydcLookAway.png",
        helpyHappy: "./assets/characters/helpy/helpyHappy.png",
        helpyIdlepng: "./assets/characters/helpy/helpyIdlepng.png",
      },
    },
    freddy: {
      name: "Freddy",
      expressions: {
        freddyAngry: "./assets/characters/freddy/freddyAngry.png",
        freddyConfused: "./assets/characters/freddy/freddyConfused.png",
        freddyGood: "./assets/characters/freddy/freddyGood.png",
        freddyNeutral: "./assets/characters/freddy/freddyNeutral.png",
      },
    },
    foxy: {
      name: "Foxy",
      expressions: {
        angry: "./assets/characters/foxy/angry.png",
        dc: "./assets/characters/foxy/dc.png",
        idle: "./assets/characters/foxy/idle.png",
        sad: "./assets/characters/foxy/sad.png",
        superAngry: "./assets/characters/foxy/superAngry.png",
        whatever: "./assets/characters/foxy/whatever.png",
      },
    },
    FT: {
      name: "FT",
      expressions: {
        FTThinking: "./assets/characters/FT/FTThinking.png",
        FTPoint: "./assets/characters/FT/FTPoint.png",
        FTHappy: "./assets/characters/FT/FTHappy.png",
      },
    },
    elias: {
      name: "Elias",
      expressions: {
        eliasAngry: "./assets/characters/elias/eliasAngry.png",
        eliasNervous: "./assets/characters/elias/eliasNervous.png",
        eliasSad: "./assets/characters/elias/eliasSad.png",
        eliasSerious: "./assets/characters/elias/eliasSerious.png",
        eliasSmile: "./assets/characters/elias/eliasSmile.png",
        eliasSmile2: "./assets/characters/elias/eliasSmile2.png",
        eliasSmileCute: "./assets/characters/elias/eliasSmileCute.png",
        eliasWave: "./assets/characters/elias/eliasWave.png",
      },
    },
    toyfreddy: {
      name: "ToyFreddy",
      expressions: {
        toyfreddyNeutral: "./assets/characters/toyfreddy/toyfreddyNeutral.png",
        toyfreddyPoint: "./assets/characters/toyfreddy/toyfreddyPoint.png",
        toyfreddyConfused: "./assets/characters/toyfreddy/toyfreddyConfused.png",
        toyfreddyHappy: "./assets/characters/toyfreddy/toyfreddyHappy.png",
        toyfreddyAngry: "./assets/characters/toyfreddy/toyfreddyAngry.png",
      },
    },
    ayano: {
      name: "Ayano",
      expressions: {
        angry1: "./assets/characters/ayano/angry1.png",
        angry2: "./assets/characters/ayano/angry2.png",
        idle1: "./assets/characters/ayano/idle1.png",
        laugh: "./assets/characters/ayano/laugh.png",
        sad1: "./assets/characters/ayano/sad1.png",
        shy1: "./assets/characters/ayano/shy1.png",
        shy2: "./assets/characters/ayano/shy2.png",
        smile1: "./assets/characters/ayano/smile1.png",
        smile2: "./assets/characters/ayano/smile2.png",
      },
    },
    sakura: {
      name: "Sakura",
      expressions: {
        blink1: "./assets/characters/sakura/blink1.png",
        dissapointed1: "./assets/characters/sakura/dissapointed1.png",
        happy1: "./assets/characters/sakura/happy1.png",
        happy2: "./assets/characters/sakura/happy2.png",
        happy3: "./assets/characters/sakura/happy3.png",
        idle1: "./assets/characters/sakura/idle1.png",
        idle2: "./assets/characters/sakura/idle2.png",
        sad1: "./assets/characters/sakura/sad1.png",
        sad2: "./assets/characters/sakura/sad2.png",
        sad3: "./assets/characters/sakura/sad3.png",
        hand: "./assets/characters/sakura/hand.png",
        scared1: "./assets/characters/sakura/scared1.png",
        special1: "./assets/characters/sakura/special1.png",
        special2: "./assets/characters/sakura/special2.png",
        special3: "./assets/characters/sakura/special3.png",
        special4: "./assets/characters/sakura/special4.png",
        special5: "./assets/characters/sakura/special5.png",
      },
    },
    akira: {
      name: "Akira",
      expressions: {
        angry1: "./assets/characters/akira/angry1.png",
        angry2: "./assets/characters/akira/angry2.png",
        concerned: "./assets/characters/akira/concerned.png",
        flirt1: "./assets/characters/akira/flirt1.png",
        flirt2: "./assets/characters/akira/flirt2.png",
        flirtIdle: "./assets/characters/akira/flirtIdle.png",
        happyIdle: "./assets/characters/akira/happyIdle.png",
        idle: "./assets/characters/akira/idle.png",
        ohReally: "./assets/characters/akira/ohReally.png",
        really: "./assets/characters/akira/really.png",
        really2: "./assets/characters/akira/really2.png",
        really3: "./assets/characters/akira/really3.png",
        really4: "./assets/characters/akira/really4.png",
        sad: "./assets/characters/akira/sad.png",
        weCanDoIt: "./assets/characters/akira/weCanDoIt.png",
        closeUpFlirt: "./assets/characters/akira/closeUpFlirt.png",
        closeUpFlirtSide: "./assets/characters/akira/closeUpFlirtSide.png",
        closeUpIdle: "./assets/characters/akira/closeUpIdle.png",
        closeUpReally: "./assets/characters/akira/closeUpReally.png",
        closeUpSmile: "./assets/characters/akira/closeUpSmile.png",
        closeUpSad: "./assets/characters/akira/closeUpSad.png",
        princess: "./assets/characters/akira/princess.png",
        special1: "./assets/characters/akira/special1.png",
        special2: "./assets/characters/akira/special2.png",
        special3: "./assets/characters/akira/special3.png",
        special4: "./assets/characters/akira/special4.png",
        special5: "./assets/characters/akira/special5.png",
        hug: "./assets/characters/akira/hug.png",
        hugV2: "./assets/characters/akira/hug.png",
        hug_forgive_me: "./assets/characters/akira/hug_forgive_me.png",
        hug_sad: "./assets/characters/akira/hug_sad.png",
        hug_smile: "./assets/characters/akira/hug_smile.png",
        hug_worried: "./assets/characters/akira/hug_worried.png",
        hug_smile_small: "./assets/characters/akira/hug_smile_small.png",
        shy: "./assets/characters/akira/shy.png",
        evilHappy1: "./assets/characters/akira/akiraEvilHappy1.png",
        evilAngry1: "./assets/characters/akira/akiraEvilAngry1.png",
        evilAnnoyed1: "./assets/characters/akira/akiraEvilAnnoyed1.png",
        evilAnnoyed2: "./assets/characters/akira/akiraEvilAnnoyed2.png",
        evilAnnoyed3: "./assets/characters/akira/akiraEvilAnnoyed3.png",
      },
    },
    shizuka: {
      name: "Shizuka",
      expressions: {
        hiddenHappy: "./assets/characters/shizuka/hiddenHappy.png",
        idle1: "./assets/characters/shizuka/idle1.png",
        idleAngry: "./assets/characters/shizuka/idleAngry.png",
        idleHappy: "./assets/characters/shizuka/idleHappy.png",
        idleLookAway: "./assets/characters/shizuka/idleLookAway.png",
        insecure: "./assets/characters/shizuka/insecure.png",
        shy1: "./assets/characters/shizuka/shy1.png",
        shy2: "./assets/characters/shizuka/shy2.png",
        shy3: "./assets/characters/shizuka/shy3.png",
      },
    },
    aya: {
      name: "Aya",
      expressions: {
        angry1: "./assets/characters/aya/angry1.png",
        angry2: "./assets/characters/aya/angry2.png",
        bow: "./assets/characters/aya/bow.png",
        embarrasedSmile: "./assets/characters/aya/embarrasedSmile.png",
        embarrasedSmileLookAway: "./assets/characters/aya/embarrasedSmileLookAway.png",
        happy1: "./assets/characters/aya/embarrasedSmileLookAway.png", 
        idleSmile: "./assets/characters/aya/idleSmile.png",
        idleSmile2: "./assets/characters/aya/idleSmile2.png",
        sad1: "./assets/characters/aya/sad1.png",
        sad2: "./assets/characters/aya/sad2.png",
        shySad: "./assets/characters/aya/shySad.png",
        sideWave: "./assets/characters/aya/sideWave.png",
        think: "./assets/characters/aya/Think.png",
      },
    },
    gfreddy: {
      name: "GFreddy",
      expressions: {
        angry: "./assets/characters/gf/gfAngry.png",
        angryPoint: "./assets/characters/gf/gfAngryPoint.png",
        confused: "./assets/characters/gf/gfConfused.png",
        happy: "./assets/characters/gf/gfHappy.png",
        idle: "./assets/characters/gf/gfIdle.png",
        lookingDown: "./assets/characters/gf/gfLookingDown.png",
        point: "./assets/characters/gf/gfPoint.png",
        sad: "./assets/characters/gf/gfSad.png",
      },
    },
    mika: {
      name: "Mika",
      expressions: {
        angry1: "./assets/characters/mika/angry1.png",
        angry2: "./assets/characters/mika/angry2.png",
        bow: "./assets/characters/mika/bow.png",
        happy1: "./assets/characters/mika/happy1.png",
        happy2: "./assets/characters/mika/happy2.png",
        happy3: "./assets/characters/mika/happy3.png",
        happyIdle1: "./assets/characters/mika/happyIdle1.png",
        listening: "./assets/characters/mika/listening.png",
        idle1: "./assets/characters/mika/idle1.png",
        ohReally1: "./assets/characters/mika/ohReally1.png",
        ohReally2: "./assets/characters/mika/ohReally2.png",
        ohReally3: "./assets/characters/mika/ohReally3.png",
        ohReally4: "./assets/characters/mika/ohReally4.png",
        onIt: "./assets/characters/mika/onIt.png",
        sad1: "./assets/characters/mika/sad1.png",
        sadLookAway: "./assets/characters/mika/sadLookAway.png",
        suprised: "./assets/characters/mika/suprised.png",
        think2: "./assets/characters/mika/think2.png",
        think3: "./assets/characters/mika/think3.png",
        think4: "./assets/characters/mika/think4.png",
        hug: "./assets/characters/mika/hug.png",
        hugClosed: "./assets/characters/mika/hugClosed.png",
      },
    },
    minako: {
      name: "Minako",
      expressions: {
        angry1: "./assets/characters/minako/angry1.png",
        angry2: "./assets/characters/minako/angry2.png",
        bow1: "./assets/characters/minako/bow1.png",
        demand1: "./assets/characters/minako/demand1.png",
        fight1: "./assets/characters/minako/fight1.png",
        flirt1: "./assets/characters/minako/flirt1.png",
        flirt2: "./assets/characters/minako/flirt2.png",
        happy1: "./assets/characters/minako/happy1.png",
        happy2: "./assets/characters/minako/happy2.png",
        happy3: "./assets/characters/minako/happy3.png",
        ignore1: "./assets/characters/minako/ignore1.png",
        ohReally1: "./assets/characters/minako/ohReally1.png",
        ohReally2: "./assets/characters/minako/ohReally2.png",
        ohReally3: "./assets/characters/minako/ohReally3.png",
        onIt1: "./assets/characters/minako/onIt1.png",
        proud1: "./assets/characters/minako/proud1.png",
        proud2: "./assets/characters/minako/proud2.png",
        sad1: "./assets/characters/minako/sad1.png",
        sad2: "./assets/characters/minako/sad2.png",
        confused: "./assets/characters/minako/confused.png",
        ohRight: "./assets/characters/minako/ohRight.png",
        ohRight2: "./assets/characters/minako/ohRight2.png",
        dark_cloth: "./assets/characters/minako/dark_cloth.png",
        blue_cloth: "./assets/characters/minako/blue_cloth.png",
        hug: "./assets/characters/minako/hug.png",
        sit_sad: "./assets/characters/minako/sit_sad.png",
        sit_sad_lookaway: "./assets/characters/minako/sit_sad_lookaway.png",
        sit_smile: "./assets/characters/minako/sit_smile.png",
      },
    },
    aiko: {
      name: "Aiko",
      expressions: {
        angry_hiding1: "./assets/characters/aiko/angry_hiding1.png",
        angry_hiding1_close: "./assets/characters/aiko/angry_hiding1.png",
        annoyed: "./assets/characters/aiko/annoyed.png",
        annoyed_close: "./assets/characters/aiko/annoyed.png",
        cry: "./assets/characters/aiko/cry.png",
        happy1: "./assets/characters/aiko/happy1.png",
        happy1_close: "./assets/characters/aiko/happy1.png",
        happy2: "./assets/characters/aiko/happy2.png",
        happy3: "./assets/characters/aiko/happy3.png",
        obsessed_happy1: "./assets/characters/aiko/obsessed_happy1.png",
        obsessed_sad1: "./assets/characters/aiko/obsessed_sad1.png",
        obsessed_sad2: "./assets/characters/aiko/obsessed_sad2.png",
        obsessed_suprised1: "./assets/characters/aiko/obsessed_suprised1.png",
        obsessed_think1: "./assets/characters/aiko/obsessed_think1.png",
        obsessed1: "./assets/characters/aiko/obsessed1.png",
        obsessed1_close: "./assets/characters/aiko/obsessed1.png",
        sad1: "./assets/characters/aiko/sad1.png",
        sad2: "./assets/characters/aiko/sad2.png",
        sweet: "./assets/characters/aiko/sweet.png",
        heart: "./assets/characters/aiko/heart.png",
        wdym: "./assets/characters/aiko/wdym.png",
      },
    },
    bedste: {
      name: "Bedste",
      expressions: {
        bgAngry: "./assets/characters/bedste/bgAngry.png",
        bgConfused: "./assets/characters/bedste/bgConfused.png",
        bgIdle: "./assets/characters/bedste/bgIdle.png",
        bgLaugh: "./assets/characters/bedste/bgLaugh.png",
        bgLookAway: "./assets/characters/bedste/bgLookAway.png",
        bgLooking: "./assets/characters/bedste/bgLooking.png",
      },
    },
    squidward: {
      name: "Squidward",
      expressions: {
        squidwardAngry: "./assets/characters/squidward/squidwardAngry.png",
        squidwardDC: "./assets/characters/squidward/squidwardDC.png",
        squidwardHappy: "./assets/characters/squidward/squidwardHappy.png"
      },
    },
    vanny: {
      name: "Vanny",
      expressions: {
        vanny: "./assets/characters/vanny/vanny.png",
      },
    },
    glitchtrap: {
      name: "Glitchtrap",
      expressions: {
        glitchtrap: "./assets/characters/glitchtrap/glitchtrap.png",
      },
    },
    principle: {
      name: "Principle",
      expressions: {
        princibleIdle: "./assets/characters/principle/princibleIdle.png",
      },
    },
    baldi: {
      name: "Baldi",
      expressions: {
        idleHappy: "./assets/characters/baldi/idleHappy.png",
        idle: "./assets/characters/baldi/idle.png",
        angry: "./assets/characters/baldi/angry.png",
      },
    },
    jacob: {
      name: "Jacob",
      expressions: {
        idle: "./assets/characters/jacob/jacob.png",
        annoyed: "./assets/characters/jacob/jacob_annoyed.png",
      },
    },
    natsuki: {
      name: "Natsuki",
      expressions: {
        genert: "./assets/characters/natsuki/genert.png",
        lille_smil: "./assets/characters/natsuki/lille_smil.png",
        neutral: "./assets/characters/natsuki/neutral.png",
        skeptisk: "./assets/characters/natsuki/skeptisk.png",
        smil: "./assets/characters/natsuki/smil.png",
        smiler: "./assets/characters/natsuki/smiler.png",
        spil_smart: "./assets/characters/natsuki/spil_smart.png",
        sur: "./assets/characters/natsuki/sur.png",
        trist: "./assets/characters/natsuki/trist.png",
        vred: "./assets/characters/natsuki/vred.png",
      },
    },
    monika: {
      name: "Monika",
      expressions: {
        flirt: "./assets/characters/monika/flirt.png",
        genert: "./assets/characters/monika/genert.png",
        griner: "./assets/characters/monika/griner.png",
        neutral: "./assets/characters/monika/neutral.png",
        smiler: "./assets/characters/monika/smiler.png",
        sur: "./assets/characters/monika/sur.png",
        trist: "./assets/characters/monika/trist.png",
        varmt_smil: "./assets/characters/monika/varmt_smil.png",
      },
    },
    sayori: {
      name: "Sayori",
      expressions: {
        forvirret: "./assets/characters/sayori/forvirret.png",
        genert: "./assets/characters/sayori/genert.png",
        glad: "./assets/characters/sayori/glad.png",
        neutral: "./assets/characters/sayori/neutral.png",
        panik: "./assets/characters/sayori/panik.png",
        skuffet: "./assets/characters/sayori/skuffet.png",
        smil_med_åbne_øjne_og_mund: "./assets/characters/sayori/smil_med_åbne_øjne_og_mund.png",
        smil_med_lukkede_øjne: "./assets/characters/sayori/smil_med_lukkede_øjne.png",
        stort_smil_med_lukkede_øjne: "./assets/characters/sayori/stort_smil_med_lukkede_øjne.png",
        sur: "./assets/characters/sayori/sur.png",
        trist: "./assets/characters/sayori/trist.png",
        utilpas: "./assets/characters/sayori/utilpas.png",
        varmt_smil: "./assets/characters/sayori/varmt_smil.png",
      },
    },
    bonnie: {
      name: "Bonnie",
      expressions: {
        chok: "./assets/characters/bonnie/chok.png",
        forvirret: "./assets/characters/bonnie/forvirret.png",
        glad: "./assets/characters/bonnie/glad.png",
        meget_glad: "./assets/characters/bonnie/meget_glad.png",
        nervøs: "./assets/characters/bonnie/nervøs.png",
        neutral: "./assets/characters/bonnie/neutral.png",
        sur: "./assets/characters/bonnie/sur.png",
        tænker: "./assets/characters/bonnie/tænker.png",
        trist_kig_væk: "./assets/characters/bonnie/trist_kig_væk.png",
        trist: "./assets/characters/bonnie/trist.png",
      },
    },
  };
  